#!/usr/bin/env python3
"""PreToolUse guard: no hand-written BibTeX.

Fabricated citations are the most common failure of LLM literature work — plausible
authors, adjacent year, a journal that never published it. Detecting them downstream is
unreliable, so this blocks at the source: a .bib file may only gain entries if it carries
the provenance header written by a citation-export tool.

Fails open. A guard that crashes must never block real work.
"""

import contextlib
import json
import os
import re
import sys

import _payload

# BibTeX entry openers, e.g. "@inproceedings{sample2025iterative,"
ENTRY_RE = re.compile(
    r"^\s*@(article|inproceedings|incollection|book|inbook|"
    r"phdthesis|mastersthesis|techreport|misc|unpublished|"
    r"conference|proceedings)\s*\{",
    re.IGNORECASE | re.MULTILINE,
)

# What a tool-generated file looks like. rs_validate writes the first form;
# common exporters write something close enough to the others.
PROVENANCE_RE = re.compile(
    r"%\s*(rs-provenance:|Generated by|Automatically generated|"
    r"This file was (auto|automatically) generated|arxiv-mcp-server|export_citations)",
    re.IGNORECASE,
)

REASON = """Hand-written BibTeX blocked (research-skills: bib_provenance_guard).

{path} would gain {n} BibTeX entr{y} with no tool provenance header.

Citation fields written from memory are plausible and frequently wrong: right-looking
author lists, adjacent years, venues that never published the paper. Generate them instead:

    arxiv -> export_citations(paper_ids: ["2503.01234", ...])

for arXiv works, or resolve the DOI through OpenAlex and generate from the returned
metadata. Keep the provenance header the exporter writes at the top of the file.

If this file genuinely is tool-generated, its header is missing — add a first line:

    % rs-provenance: tool=<name> date=<YYYY-MM-DD>
"""


def deny(reason: str) -> None:
    json.dump(_payload.deny(reason), sys.stdout)
    sys.exit(0)


def main() -> None:
    payload = json.load(sys.stdin)
    tool_input = payload.get("tool_input") or {}

    paths = [p for p in _payload.targets(tool_input) if p.endswith(".bib")]
    if not paths:
        return
    path = paths[0]

    # Write carries the whole file; Edit carries only the replacement text.
    is_full_write = tool_input.get("content") is not None
    incoming = _payload.written_text(tool_input)
    if not incoming:
        return

    entries = ENTRY_RE.findall(incoming)
    if not entries:
        return  # touching a .bib without adding entries is fine

    if PROVENANCE_RE.search(incoming):
        return

    # An Edit appends to a file that may already be marked as tool-generated.
    if not is_full_write and os.path.exists(path):
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                if PROVENANCE_RE.search(fh.read(4096)):
                    return
        except OSError:
            return  # unreadable: fail open

    n = len(entries)
    deny(REASON.format(path=path, n=n, y="y" if n == 1 else "ies"))


if __name__ == "__main__":
    # Fail open, always: a guard that raises inside the hook runner blocks real work,
    # which is strictly worse than the guard not existing.
    with contextlib.suppress(Exception):
        main()
    sys.exit(0)
