#!/usr/bin/env python3
"""PreToolUse guard for BibTeX provenance.

A broad file header is not evidence that a newly appended entry came from a tool.  New or
modified entries therefore need a per-entry attestation binding ``key``, a stable
identifier, ``tool`` and ``date``.  This is an integrity tripwire, not cryptographic
provenance: an attestation can still be forged.
"""

from __future__ import annotations

import contextlib
import datetime
import json
import os
import re
import sys

import _payload

ENTRY_RE = re.compile(
    r"^\s*@(?!(?:string|preamble|comment)\b)\w+\s*[\{\(]\s*([^,\s]+)",
    re.IGNORECASE | re.MULTILINE,
)
LEGACY_HEADER_RE = re.compile(
    r"^\s*%\s*(?:rs-provenance:|Generated by|Automatically generated|"
    r"This file was (?:auto|automatically) generated|arxiv-mcp-server|export_citations)",
    re.IGNORECASE | re.MULTILINE,
)
ATTESTATION_RE = re.compile(
    r"^\s*%\s*rs-provenance:\s*"
    r"key=(?P<key>\S+)\s+id=(?P<id>\S+)\s+tool=(?P<tool>\S+)\s+"
    r"date=(?P<date>\d{4}-\d{2}-\d{2})\s*$",
    re.IGNORECASE | re.MULTILINE,
)

REASON = """BibTeX write blocked (ai-research-skills: bib_provenance_guard).

{path} would add or modify {keys} without a strict per-entry rs-provenance attestation.
The attestation must bind the citation key, a stable identifier, the exporting tool, and
an ISO date, for example:

    % rs-provenance: key=sample2025iterative id=arXiv:2503.01234 tool=arxiv.export_citations date=2026-08-03

A legacy file-level Generated by/rs-provenance header only preserves unchanged old
entries; it cannot authorise an append or a full rewrite.  Attestations can be forged —
run ars-verify for external identifier resolution.
"""


def deny(reason: str) -> None:
    json.dump(_payload.deny(reason), sys.stdout)
    sys.exit(0)


def _entry_blocks(text: str) -> list[tuple[str, str]]:
    """Return entries in source order; never silently overwrite duplicate keys."""
    matches = list(ENTRY_RE.finditer(text))
    return [
        (
            match.group(1),
            text[
                match.start() : (
                    matches[index + 1].start() if index + 1 < len(matches) else len(text)
                )
            ],
        )
        for index, match in enumerate(matches)
    ]


def _entry_map(entries: list[tuple[str, str]]) -> dict[str, str] | None:
    out: dict[str, str] = {}
    for key, body in entries:
        if key in out:
            return None
        out[key] = body
    return out


def _attestations(text: str) -> dict[int, list[dict[str, str]]]:
    """Bind each comment only to the one next entry occurrence."""
    entries = list(ENTRY_RE.finditer(text))
    out: dict[int, list[dict[str, str]]] = {}
    for match in ATTESTATION_RE.finditer(text):
        for index, entry in enumerate(entries):
            if entry.start() > match.end():
                out.setdefault(index, []).append(match.groupdict())
                break
    return out


def _corpus_records(cwd: str, path: str) -> tuple[bool, dict[str, str | None]]:
    """Return ``(corpus_found, key -> id)`` for refs.bib's sibling only.

    Looking through every survey directory made a bibliography in one survey inherit an
    identifier from another.  A discovered corpus with a missing/duplicate key is
    evidence of an invalid binding, not the same thing as no corpus.
    """
    absolute = os.path.abspath(path if os.path.isabs(path) else os.path.join(cwd, path))
    candidate = os.path.join(os.path.dirname(absolute), "corpus.jsonl")
    if not os.path.isfile(candidate):
        return False, {}
    records: dict[str, str | None] = {}
    try:
        with open(candidate, encoding="utf-8") as fh:
            for raw in fh:
                try:
                    record = json.loads(raw)
                except json.JSONDecodeError:
                    continue
                if not isinstance(record, dict):
                    continue
                key = record.get("key")
                identifier = record.get("id") or record.get("openalex_id")
                if not isinstance(key, str) or not key:
                    continue
                if key in records:
                    records[key] = None
                elif isinstance(identifier, str) and identifier:
                    records[key] = identifier
                else:
                    records[key] = None
    except OSError:
        return True, {}
    return True, records


def _strict_ok(
    attestation: dict[str, str] | None,
    key: str,
    corpus_found: bool,
    corpus: dict[str, str | None],
) -> bool:
    if not attestation or attestation.get("key") != key:
        return False
    try:
        datetime.date.fromisoformat(attestation.get("date", ""))
    except (TypeError, ValueError):
        return False
    if not attestation.get("tool"):
        return False
    if not corpus_found:
        return True
    expected = corpus.get(key)
    return expected is not None and attestation.get("id") == expected


def _changed_keys(
    old_entries: list[tuple[str, str]], incoming_entries: list[tuple[str, str]]
) -> list[str]:
    old = _entry_map(old_entries)
    incoming = _entry_map(incoming_entries)
    if old is None or incoming is None:
        return [key for key, _body in incoming_entries]
    return [key for key, body in incoming_entries if old.get(key) != body]


def _read_text(path: str) -> str:
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            return fh.read()
    except OSError:
        return ""


def _operation_path(cwd: str, path: str) -> str:
    return os.path.abspath(path if os.path.isabs(path) else os.path.join(cwd, path))


def _move_complete(
    op: _payload.WriteOperation, cwd: str, incoming: list[tuple[str, str]], destination: str
) -> tuple[bool, str]:
    """Require enough information to reconstruct a moved BibTeX file."""
    old_path = _operation_path(cwd, op.old_path or "")
    source_text = _read_text(old_path) if op.old_path else ""
    source_entries = _entry_blocks(source_text)
    destination_entries = (
        _entry_blocks(_read_text(destination)) if os.path.exists(destination) else []
    )
    if source_entries:
        source_keys = {key for key, _body in source_entries}
        incoming_keys = {key for key, _body in incoming}
        # A Move carrying only a changed field cannot prove the final file.  A complete
        # move must carry every source entry (one-entry files are the common case).
        if incoming_keys != source_keys:
            return False, "Move of an existing .bib requires the complete final entry set"
    elif not incoming and destination_entries:
        return False, "Move of an existing .bib has no reconstructable final entry"
    elif op.old_path and not source_text and not incoming:
        return False, "Move source could not be read or reconstructed"
    return True, ""


def check_operation(op: _payload.WriteOperation, cwd: str) -> tuple[bool, str]:
    path = op.path
    fs_path = _operation_path(cwd, path)
    if not path.lower().endswith(".bib"):
        return True, ""
    if op.kind == "delete":
        return True, ""

    incoming = op.text
    incoming_entries = _entry_blocks(incoming)
    incoming_map = _entry_map(incoming_entries)
    if incoming_map is None:
        return False, "BibTeX write contains duplicate citation keys"

    old_text = _read_text(fs_path) if os.path.exists(fs_path) else ""
    old_entries = _entry_blocks(old_text)
    if _entry_map(old_entries) is None:
        return False, "existing .bib contains duplicate citation keys"

    if op.kind == "move":
        complete, move_reason = _move_complete(op, cwd, incoming_entries, fs_path)
        if not complete:
            return False, move_reason

    if not incoming:
        # A .bib edit with no complete entry can still modify an old entry.  Be
        # conservative when the target/source already contains BibTeX entries.
        if op.kind not in ("write", "add") and (old_entries or op.old_path):
            return (
                False,
                "an edit to an existing BibTeX entry has no reconstructable attestation",
            )
        return True, ""

    # An Edit may carry a replacement field rather than an entire @entry.  It cannot
    # prove which entry was modified, so reject it if it touches a populated bib file.
    if not incoming_entries and op.kind not in ("write", "add"):
        if old_entries or op.old_path:
            return False, "an edit to an existing BibTeX entry has no attestation"
        return True, ""
    if not incoming_entries:
        return True, ""

    legacy = bool(LEGACY_HEADER_RE.search(old_text))
    corpus_found, corpus = _corpus_records(cwd, fs_path)
    changed = _changed_keys(old_entries, incoming_entries)
    attached = _attestations(incoming)
    attestations_by_key: dict[str, dict[str, str]] = {}
    for index, (key, _body) in enumerate(incoming_entries):
        values = attached.get(index, [])
        if len(values) == 1:
            attestations_by_key[key] = values[0]
        elif len(values) > 1:
            return False, f"citation key {key} has more than one attestation"

    old_map = _entry_map(old_entries) or {}
    incoming_by_key = _entry_map(incoming_entries) or {}
    bad: list[str] = []
    for key in changed:
        if _strict_ok(attestations_by_key.get(key), key, corpus_found, corpus):
            continue
        # Only an unchanged old entry may use the broad legacy header.  A new entry in a
        # full rewrite is changed even if the old file had a valid header.
        if legacy and old_map.get(key) == incoming_by_key.get(key):
            continue
        bad.append(key)
    if bad:
        return False, REASON.format(path=path, keys=", ".join(sorted(set(bad))))
    return True, ""


def main() -> None:
    payload = json.load(sys.stdin)
    cwd = payload.get("cwd") or os.getcwd()
    tool_input = payload.get("tool_input") or {}
    for operation in _payload.operations(tool_input):
        ok, reason = check_operation(operation, cwd)
        if not ok:
            deny(reason)


if __name__ == "__main__":
    with contextlib.suppress(Exception):
        main()
    sys.exit(0)
